[package]
name = "rustun"
version = "0.1.5"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "A library for implementing STUN server and client asynchronously"
homepage = "https://github.com/sile/rustun"
repository = "https://github.com/sile/rustun"
readme = "README.md"
keywords = ["STUN", "asynchronous"]
categories = ["asynchronous", "network-programming"]
license = "MIT"

[badges]
travis-ci = {repository = "sile/rustun"}

[dependencies]
crc = "1"
md5 = "0.3"
hmac-sha1 = "0.1"
slog = "2"
rand = "0.5"
fibers = "0.1"
futures = "0.1"
trackable = "0.2"
handy_async = "0.2"

[dev-dependencies]
clap = "2"
sloggers = "0.2"
